name: Auto Update README with User Activity

on:
  schedule:
    - cron: "*/30 * * * *"   # 每 30 分鐘執行一次
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch Recent Activity for User
      run: |
        USERNAME="saisai568" 
        echo "<!--START_SECTION:activity-->" > activity.md
        curl -s "https://api.github.com/users/$USERNAME/events" | \
        jq -r '.[] | select(.type=="PushEvent" or .type=="PullRequestEvent") | "- \(.type): \(.repo.name)"' | head -n 5 >> activity.md
        echo "<!--END_SECTION:activity-->" >> activity.md

    - name: Update README section
      run: |
        awk '
          /<!--START_SECTION:activity-->/ {print; system("cat activity.md"); skip=1; next}
          /<!--END_SECTION:activity-->/ {skip=0}
          !skip
        ' README.md > README.tmp && mv README.tmp README.md

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: auto-update activity section"
        branch: main
        commit_user_name: github-actions
        commit_user_email: actions@github.com
        token: ${{ secrets.REPO_TOKEN }}
